#+TITLE: Filetags

A novel way to automatically organize your files via symlinks by "tagging" them with filename cookies.

* Purpose

Imagine that you're using a music DAW (Digital Audio Workstation) and want to mark several files as "favorite" so you can quickly come back to them later. Most DAWs don't provide such functionality, so the only realistic options are to either copy or move your favorite samples to a dedicated "favorites" directory. This is not very ideal. It can be very time-consuming and meticulous.

So what if there was a way to automatically organize any arbitrary file to a dedicated directory, without any file duplication or moving? and without every having to leave your DAW for any of the sorting?

This project seeks to solve exactly that, by automatically symlinking files with a matching filename cookie, to a specified directory.

So for example, if there's a sample I really like, all I need to do is rename the file to include a filename cookie, such as ="^_.*"= (a filename prefixed with an underscore) to automatically symlink that file to my "favorites" directory. Thus, streamlining this style of file organization by tenfold, and making this possible no matter the front-end, as long as it can rename files.

And because it's file-agnostic, it can be used to organize your photos, movies, documents, and anything else, as long as it's a file, and can be renamed.

* How does it work?

It runs a daemon in the background that recursively monitors all files from a directory for changes in filename. When it observes a file rename, it matches the filename against a specified filename cookie Regex, and if it matches, symlink accordingly.

TODO: more info.

* Features

- specify multiple "rules", where each rule specifies directories to monitor and directories to symlink to (and other settings).


