
general:

default_settings:

rules:

  - name: "favorite samples"
    watch_dirs:
      - "~/Music/prod/Samples/sample_packs/"
    link_dirs:
      - "~/Music/prod/Samples/_Favorites/"
    regex:
      - "^_.*"
    settings:
