
rules:
  - name: "favorite samples"
    watch_dirs:
      - "~/Music/prod/Samples/sample_packs/"
      - "~/Music/prod/Samples/_my-samples/"
    link_dirs:
      - "~/Music/prod/Samples/_Favorites/"
    regex:
      - "^_.*"
